import img from "./img/adve002.png";

export const data = [
  [
    { service: "facebook" },
    {
      id: "fb-acc",
      title: "FB Profile",
      desc: "Selling Facebook profiles means offering aged or ready-made accounts, often used for ads—but it's against Facebook’s rules.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746805976/Facebook_logo__square_tqqd1z.png",
    },
    {
      id: "fb-bm",
      title: "FB BM",
      desc: "Selling Facebook BM means offering aged or ready-made accounts, often used for ads—but it's against Facebook’s rules.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746805977/233VSmAsi5mRqo1hd77OZcJQh2c_1_zlzniz.png",
    },
    {
      id: "fb-page",
      title: "FB Pages",
      desc: "Selling Facebook Pages means offering aged or ready-made accounts, often used for ads—but it's against Facebook’s rules.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746805977/Facebook-Page-Logo_vd61aq.png",
    },
  ],
  [
    { service: "tiktok" },
    {
      id: "tk-acc",
      title: "Tiktok Account",
      desc: "Selling Tiktok Account means offering aged or ready-made accounts, often used for ads—but it's against Tiktok's rules.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746806243/tiktok_hkwo2g.jpg",
    },
    {
      id: "tk-ad",
      title: "Tiktok Ads",
      desc: "Selling Tiktok Ads means offering aged or ready-made accounts, often used for ads—but it's against Tiktok's rules.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746806243/TikTokForBusiness_zu1qql.jpg",
    },
    {
      id: "tk-beta",
      title: "Tiktok Beta",
      desc: "Selling Tiktok Beta means offering aged or ready-made accounts, often used for ads—but it's against Tiktok's rules.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746806242/1920x1080bb-80_hrvvfi.png",
    },
  ],
  [
    { service: "services" },
    {
      id: "run-ads",
      title: "Ad Campaigns & Page Management",
      desc: "We offer expert ad launches and page management on Facebook, Instagram, and TikTok to boost engagement and drive growth.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746806413/hero-image_yggss1.jpg",
    },
    {
      id: "followers",
      title: "Followers Boost",
      desc: "Grow your followers fast on Instagram, Facebook, and TikTok with our reliable and instant boosting service.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746806414/%D9%84%D9%82%D8%B7%D8%A9_%D8%A7%D9%84%D8%B4%D8%A7%D8%B4%D8%A9_2025-05-09_122448_l9ww87.png",
    },
    {
      id: "likes",
      title: "Like Booster",
      desc: "SGet more likes instantly on Instagram, Facebook, and TikTok with our fast and safe boosting service.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746806414/%D9%84%D9%82%D8%B7%D8%A9_%D8%A7%D9%84%D8%B4%D8%A7%D8%B4%D8%A9_2025-05-09_122504_dp2ltj.png",
    },
    {
      id: "consult",
      title: "Consultation",
      desc: "A consultation business offers expert advice to help clients solve problems, improve performance, and reach their goals efficiently.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746806413/ba033a2133ee00f0bbb0c1c06c4b0d28c7e3ccf5_tx1nmq.jpg",
    },
  ],
  [
    { service: "courses" },
    {
      id: "tiktokads",
      title: "TikTok Ads",
      desc: "Master TikTok ads with our course, covering campaign creation, audience targeting, and optimization to boost your brand's reach and conversions.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807043/Tiktok-Ads_zmqwua.png",
    },
    {
      id: "fbads",
      title: "FB Ads",
      desc: "Learn how to create, manage, and optimize Facebook ad campaigns to reach your target audience, increase engagement, and drive conversions effectively.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807042/1678790595-B2oqSItsSB_x80g49.png",
    },
    {
      id: "marketing",
      title: "Marketing",
      desc: "Learn key strategies to boost brand visibility, engage your audience, and drive sales through social media, SEO, and paid ads.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807042/New-Project-21_oevmlr.jpg",
    },
    {
      id: "ecom",
      title: "E-commerce",
      desc: "Master online store setup, marketing, and sales strategies to grow your e-commerce business effectively.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807042/certification-course-in-ecommerce_mijmrt.jpg",
    },
  ],
  [
    { service: "accounts" },
    {
      id: "wise",
      title: "Wise Account",
      desc: "Buy or sell Wise accounts securely with our trusted and efficient service.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807494/transferwise-icon-filled-256_p0se6h.png",
    },
    {
      id: "revolut",
      title: "Revolut Account",
      desc: "Buy or sell Revolut accounts securely with our fast and reliable service.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807494/revolut-logo-new_ublaqp.jpg",
    },
    {
      id: "myfin",
      title: "MyFin Account",
      desc: "Buy or sell MyFin accounts securely with our smooth and reliable service.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807499/unnamed_4_ehoihl.jpg",
    },
    {
      id: "paypal",
      title: "Paypal Account",
      desc: "We offer a secure service for buying or selling PayPal accounts, ensuring smooth transactions and safe account transfers for your business needs.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807495/unnamed_2_owwp4v.png",
    },
    {
      id: "ebay",
      title: "Ebay Account",
      desc: "Our service helps you buy or sell eBay accounts securely, with a smooth transfer process to ensure your online business runs effortlessly.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807500/unnamed_y0fxej.jpg",
    },
    {
      id: "etsy",
      title: "Etsy Account",
      desc: "We offer a reliable service to help you buy or sell Etsy accounts, ensuring secure transactions and a smooth process for setting up your online shop.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807494/etsy-logo-logo_klu6li.png",
    },
  ],
  [
    { service: "subscriptions" },
    {
      id: "canvapro",
      title: "Canva Pro",
      desc: "Get access to Canva Pro accounts securely with our reliable service for enhanced design tools and features.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807841/canva-pro-lifetime-access-selar.co-65b6705f9cd19_cgqlvv.jpg",
    },
    {
      id: "gpt4",
      title: "ChatGTP 4+",
      desc: "Get access to the advanced features of ChatGPT-4+ with our secure service for enhanced AI capabilities and improved performance.",
      price: "2",
      img: "https://res.cloudinary.com/dsqon0kae/image/upload/v1746807842/jtn1726044606_t59ase.jpg",
    },
  ],
  [
    { service: "package" },
    {
      id: "#",
      title: "Comming Soon",
      desc: "Comming Soon",
      price: "#",
      img: `https://c7.alamy.com/comp/2H59EKF/colorful-coming-soon-composition-with-flat-design-coming-soon-sign-color-vector-illustration-2H59EKF.jpg`,
    },
  ],
  [
    { service: "other" },
    {
      id: "#",
      title: "Comming Soon",
      desc: "Comming Soon",
      price: "#",
      img: `https://c7.alamy.com/comp/2H59EKF/colorful-coming-soon-composition-with-flat-design-coming-soon-sign-color-vector-illustration-2H59EKF.jpg`,
    },
  ],
];
